codacy/codacy-orbs

src/jobs/helm_push.yaml
This change allows us to re-run the same workflow multiple times without having to manually delete charts from the chart museum
=> Add --force option to helm push command

src/jobs/sbt.yml
This fixes the certificates problem:
```
[error] Server access Error: Received fatal alert: handshake_failure url=https://repo.eclipse.org/content/groups/releases/com/codacy/database_2.11/15.3.0/database_2.11-15.3.0.pom
```
you might be experiencing in CIs
=> fix: Set OpenJDK before running sbt tasks

src/commands/sbt_cached.yml, src/jobs/sbt.yml
I finally discovered one of the reasons for the caches to be not working in most of our CircleCI setups:
https://github.com/sbt/sbt/issues/4168
The issue is still open and I'm pretty sure that this is not a final fix, rather is an improvement.
e.g.:
https://circleci.com/workflow-run/5c10aea5-7eba-4bb0-ae03-1f3e52b7f5da
the `populate_cahe_and_compile` step got a 7 minutes boost, but the tests are still taking almost the same time as before.
=> fix: Sbt caching

src/jobs/sbt_osx.yml
Usually we need to cache only specific artifacts produced on OsX is irrelevant to compress the targets and it fails on ci.
=> fix: Do not compress targets on osx

src/jobs/deploy_to_selfhosted.yml
Not sleeping in between the trigger and the pooling would cause the returned URL to be invalid.
=> fix: add sleep between trigger and polling

src/executors/machine.yml
Current java seems to be a buggy version causing some issues with `java.net.URL`
=> Trying to update the image to see if java is bumped

src/jobs/microk8s_install.yml
It is required for helm3+ for the namespace to be created before
=> Create the namespace explicitly

src/executors/do.yml, src/jobs/deploy_to_selfhosted.yml
The latest ci-do image consumes helm3 and installs the latest helm poll plugin as well.
=> fix: Make helm poll self hosted helm3 compliant

src/jobs/sbt.yml
Sometimes the target directory delete step fails with
```bash
rm: cannot remove './.../target': No such file or directory
```
like [here](https://app.circleci.com/pipelines/github/codacy/codacy-plugins/55/workflows/e4eb228a-4ecb-44c0-ba00-f60dce8a8139/jobs/118).
With this patch it forces the deletion without returning errors in case of the files to delete don't exist.
Here same PR passes using this patch: https://app.circleci.com/pipelines/github/codacy/codacy-plugins/65/workflows/7f0fab17-6fb4-4935-a8d4-856026098c05/jobs/138
=> fix: Use force delete for targets directories

src/executors/do.yml
This bump includes a bump for the shipped helm version, which should resolve the ```Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials``` error that we have been getting.
=> bump: Updated ci-do image version on executor

src/jobs/microk8s_install.yml
Tests are still failing because I missed a change: when we are polling for results of the analysis we have to make the call using the uniquename of the user that owns the project - this user changed from `jaime_1` to `reliability`
=> fix: adapt call for commit anaysis results endpoint to use new test user

src/jobs/sbt_osx.yml
**TL/DR:** The version of Homebrew on Circle CI images is outdated (2.2.2 from over a year ago) and has an issue that prevents the correct auto-update, necessary for fetching OpenJDK from the correct mirror and thus avoiding Bintray.
Workflows using this Orb [are failing](https://app.circleci.com/pipelines/github/codacy/codacy-coverage-reporter/920/workflows/01517e8d-fea5-499c-943a-c331c7f54ca3/jobs/7995/steps) because OpenJDK had a dependency from Bintray:
```
brew install sbt
...
==> Downloading https://homebrew.bintray.com/openjdk-15.0.2.catalina.bottle.tar.
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading …
```
=> fix: Call brew update explicitly to fix Bintray dependency

src/jobs/sbt_osx.yml
The update from https://github.com/codacy/codacy-orbs/pull/173 wasn't enough to solve the issue as installing `sbt` reinstalled the openjdk@18 as a dependency:
https://app.circleci.com/pipelines/github/codacy/codacy-faux-pas/49/workflows/4b227b08-309e-415f-82f9-9f2a6c2a7d5c/jobs/308?invite=true#step-102-159
=> fix: Correctly set up and pin openjdk@8

src/jobs/sbt_docker.yml
Remote docker is expensive and takes time.
We want to disable it when it's not needed.
=> Add setup_remote_docker parameter in sbt_docker

src/commands/sbt_cached.yml, src/jobs/sbt.yml, src/jobs/sbt_docker.yml
We want to enable coverage only in CI.
To do that we want to write a custom sbt file before sbt starts.
Since in server-client mode sbt is started by the orb, we need a hook to run some script before sbt starts.
now we can do:
```yaml
steps_before_sbt:
- run:
name: "Enable Coverage"
command: echo "ThisBuild / coverageEnabled := true" > coverage.sbt
steps:
- run:
name: "sbt stuff"
command: sbt compile
```
=> feature: Add `steps_before_sbt` to sbt job

src/commands/sbt_cached.yml
Tested [here](https://app.circleci.com/pipelines/github/codacy/codacy-website/2370/workflows/2c9c7490-ba2a-4389-9581-fad4d6e780d4/jobs/12854)
=> fix: Kill job when Sbt fails to start

src/jobs/sbt_osx.yml
Reverts #146. The previous workaround should no longer be necessary, as CircleCI is already updating Homebrew on macOS images as a workaround on their side:
https://discuss.circleci.com/t/macos-image-users-homebrew-brownout-2021-04-26/39872/2
=> clean: Revert workaround from #146

src/executors/aws.yml
Use ci-aws:8.2.0 in aws executor to have helm clean function available.
=> bump: Upgrade ci-aws to 8.2 to get helm ssm -c

src/jobs/helm_aws.yml
This is needed for the dummy values files to be persisted before helm push (helm puss executes in a following step)
=> feature: add support for persisting to workspace in helm_aws job

src/executors/machine.yml
Upgrade to latest version of ubuntu 20.04. This upgrades docker version and fixes issues building docker images.
=> bump: machine executor ubuntu-2004:202107-02->2022.10.1

src/jobs/checkout_and_version.yml
Fixes the issue with github.com host key change, and makes this step more resilient by always getting the latest host keys from github.
=> fix: Update github host keys

src/jobs/checkout_and_version.yml
Fixes an issue where a broken version of the curl binary was being installed and breaking pipeline execution.
=> fix: issue with curl binary in checkout_and_version

src/jobs/update_dev_env_approval_status_check.yml
Some notes:
- Only added one parameter, because the rest can be obtained directly from CircleCI variables
- Bash script based on the solution provided [here](https://federicoterzi.com/blog/solving-github-status-stuck-on-pending-with-circlecis-approvals/)
- Solution only works for one dev environment, needs more tweeks to support multiples (but I think it's fine like this for now, we need to push this forward)
=> feature: Add job to support GitHub status check overwrite

src/jobs/sbt.yml, src/jobs/sbt_docker.yml
Adds the ability to setup the `docker scout` plugin, which replaces the [deprecated](https://github.com/docker/scan-cli-plugin) `docker scan` command, to the `sbt` and `sbt_docker` steps, which are commonly used to build docker images.
To use it remove all `docker scan` commands,  set `setup_docker_scout: true` in the `codacy/sbt` or `codacy/sbt_docker` step, and run:
```
docker scout cves ubuntu --only-fixed --only-severity high,critical --exit-code
```
=> feature: add docker scout plugin

src/commands/sbt_cached.yml
Reverts codacy/codacy-orbs#189
Guardrail is getting better and our builds are getting slower. It might be interesting to try this again
=> Revert "fix: Avoid caching targets in sbt"

src/jobs/shell.yml
When I added the `steps` parameter I forgot to set a default for `cmd`
=> fix: Add default value to `cmd` in `shell` orb

src/jobs/wait_for_workflows.yml
`$CIRCLE_TOKEN` is not defined when running PRs from forks quoting the env variable value makes it pass an empty string which is passed as an empty token to the CircleCI API, which works fine when a project is public.
Example: https://app.circleci.com/pipelines/github/codacy/codacy-coverage-reporter/1594/workflows/52c97ab7-77b9-4d01-9a4d-170a59e9c28e/jobs/15313
=> fix: Allow running wait_for_workflows in forks

.circleci/config.yml, src/commands/run_aws.yml, src/commands/run_skip_ssh.yml, src/commands/sbt_cached.yml, src/jobs/aws_deploy.yml, src/jobs/deploy_to_selfhosted.yml, src/jobs/helm_promote.yaml, src/jobs/helm_push.yaml, src/jobs/microk8s_install.yml, src/jobs/sbt.yml, src/jobs/tag_version.yml
[CY-7236](https://codacy.atlassian.net/browse/CY-7236)
CircleCI will deprecate step 'deploy', therefore we need to migrate to the least impacting option, using step 'run' with some safeguards not to run some instructions on 'Rerun job with SSH'.
[CY-7236]: https://codacy.atlassian.net/browse/CY-7236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> breaking: Deprecate step 'deploy'

src/jobs/sbt.yml, src/jobs/sbt_docker.yml
Currently we spend time to compress and clean the caches every time, even when we don't actually save it.
This PR makes it configurable so the CI does the compression step only when needed.
=> feature: Add `save_cache` parameter to sbt jobs

src/commands/sbt_cached.yml
I was suspicious of the cache we have in worker which is 6 GBs and I found this:
So, I'm now cleaning the `jar` before storing the cache, so old jars are dropped.
In worker:
Before:
After:
=> feature: Delete jars before caching targets

src/jobs/sbt_docker.yml
This is giving problems in newer orb versions
=> fix: Switch default for `use_sbt_native_client` in `sbt_docker`
