codacy/codacy-orbs

src/executors/aws.yml

bump ci-aws

---

src/jobs/publish_ghr.yml

Add an orb to publish to Github Releases

---

src/executors/aws.yml

bump: ci-aws 3.7.2 -> 3.7.4

---

src/jobs/publish_bintray.yml

Add publish to bintray orb

---

src/jobs/checkout_and_version.yml

Add update_submodules parameter for checkout_and_version orb

---

src/executors/aws.yml

bump: ci-aws 3.7.4 -> 3.8.0

---

src/jobs/checkout_and_version.yml

git-version 1.1.0 has been published to support this change
https://circleci.com/gh/codacy/git-version/87

feature: support custom branches on git version

---

src/jobs/publish_docker.yml

feature: Add job to publish to Docker Hub

---

src/commands/sbt_cached.yml
src/examples/example.yml
src/jobs/sbt.yml

Add an optional step to upload the test results back to CircleCI for display in the UI

Add optional store test results step

---

src/jobs/deploy_to_selfhosted.yml

For convenience, we can now return the remote workflow url.
This should make issue investigations easier.

feature: return remote workflow id on remote trigger

---

src/jobs/deploy_to_selfhosted.yml

I forgot to add this so that helm poll can point at the correct cluster

fix: add set cluster context for helm poll

---

src/jobs/tag_version.yml

Adds personal token / app password support for pushing tags via https

Add personal token support

---

src/jobs/microk8s_install.yml

breaking: allow helm3 to be installed in microk8s

---

src/jobs/microk8s_install.yml

This fixes "Error: Kubernetes cluster unreachable"
Know more at https://worklifenotes.com/2020/01/22/how-to-make-microk8s-work-with-helm/

fix: Add microk8s configuration to kube config

---

src/jobs/deploy_to_selfhosted.yml

This will match the fullnameOverrides of the components

fix: Prefix release name with codacy

---

src/jobs/deploy_to_selfhosted.yml

values-production is no longer required.

feature: Allow path to values file to be overriden

---

src/commands/sbt_cached.yml
src/jobs/sbt.yml

Should fix https://bitbucket.org/qamine/website-infrastructure/pull-requests/50/bump-update-engine-api

feature: Allow customization of no_output_timeout

---

src/jobs/microk8s_install.yml

This will allow us to remove the base users of every installation without breaking these tests :)

fix: allow test to run without base users (add user for testing) CY-1441

---

src/jobs/deploy_to_selfhosted.yml

These values are now set in codacy-ingress deploy to sh

refactor: Removed deploy sh ingress related sets

---

src/jobs/pulse_integration.yml

Depends on this: https://github.com/codacy/pulse-event-cli/pull/2

feature: Simplify pulse integration using new version

---

src/jobs/publish_s3.yml

The orb is currently published as: `codacy/base@dev:5.2.0-publishs3orb.2.d882b05`

feature: Add publish_s3 orb

---

src/jobs/publish_docker.yml

Fixes an issue where parameters were not expanded in the default cmd

fix: default cmd parameter not working

---

src/commands/sbt_cached.yml
src/jobs/sbt.yml
src/jobs/sbt_osx.yml

Add `use_sbt_native_image` parameter to run Sbt in server client mode

feature: Support passing `steps` to sbt jobs

---

src/executors/jdk.yml
src/jobs/sbt_docker.yml

This fixes the issues we were having with native images not working properly.
PS: Don't use rolling versions 🙈

fix: Revert openjdk image and remove bundled sbt when installing it

---

src/executors/aws.yml

Use latest ci-aws to fix hlem-ssm installation issues

fix: Use ci-aws:9.0.1 which fixes helm-ssm installation issues

---

src/@orb.yml
src/jobs/aws_deploy.yml
src/jobs/helm_aws.yml

Adds the option to notify slack on failure/success of helm_aws and aws_deploy steps.

feature: Add slack notifications to helm_aws and aws_deploy

---

src/executors/aws.yml

bump: Upgrade ci-aws to 9.0.3

---

src/commands/build_and_publish_docker.yml
src/executors/go.yml
src/jobs/go.yml

Closes [REL-1551](https://codacy.atlassian.net/browse/REL-1551)
[REL-1551]: https://codacy.atlassian.net/browse/REL-1551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature: Add Go job
